import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { NextIntlClientProvider } from "next-intl"
import "./globals.css"
import FooterUI from "./th_3/_components/footer"
import { Toaster } from "@/components/ui/sonner"
import dynamic from "next/dynamic"
import { Providers } from "./th_3/providers"
const Header = dynamic(() => import('./th_3/_components/header'), { ssr: true })
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
}

const ab = Inter({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${ab.variable} antialiased`}>
      <body data-new-gr-c-s-check-loaded="14.1271.0" data-gr-ext-installed="" cz-shortcut-listen="true" >
        <Providers>
          <NextIntlClientProvider>
            <div style={{ display: "contents" }}>
              <Header />
              {children}
              <FooterUI />
            </div>
          </NextIntlClientProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
