"use client"

import React, { useEffect, useRef, useState } from "react"
import { createPortal } from "react-dom"

interface ShadowRootProps {
  children: React.ReactNode
}

const ShadowRoot = ({ children }: ShadowRootProps) => {
  const [container, setContainer] = useState<HTMLDivElement | null>(null)

  const onHostRef = React.useCallback((node: HTMLDivElement | null) => {
    if (node) {
      // Check if shadow root already exists (important for Fast Refresh)
      let root = node.shadowRoot
      if (!root) {
        root = node.attachShadow({ mode: "open" })
      }

      // Clear any existing content if we're re-initializing
      root.innerHTML = ""

      // Create a style element to handle potential FOUC or base styles
      const baseStyle = document.createElement("style")
      baseStyle.textContent = `
        :host {
          display: block;
          width: 100%;
        }
      `
      root.appendChild(baseStyle)

      // Inject global styles into shadow root
      // This includes Tailwind styles generated by Next.js
      const styles = document.querySelectorAll("style, link[rel='stylesheet']")
      styles.forEach((style) => {
        const clone = style.cloneNode(true)
        root?.appendChild(clone)
      })

      const innerContainer = document.createElement("div")
      innerContainer.style.width = "100%"
      root.appendChild(innerContainer)
      setContainer(innerContainer)
    }
  }, [])

  return (
    <div ref={onHostRef} style={{ display: "contents" }}>
      {container && createPortal(children, container)}
    </div>
  )
}

export default ShadowRoot
