import type { Metadata } from "next"
import { ABeeZee } from "next/font/google"
import { NextIntlClientProvider } from "next-intl"

import "./globals.css"

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
}

const ab = ABeeZee({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${ab.variable} antialiased`}>
      <body>
        <NextIntlClientProvider>
          <div style={{ display: "contents" }}>{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
