// import type { Metadata } from "next"

import { Geist_Mono, Inter } from "next/font/google"
import { NextIntlClientProvider } from "next-intl"
import { cookies } from "next/headers"
import "./globals.css"
import { Header } from "./th_2/_components/header/header"
import { Footer } from "./th_2/_components/footer/footer"
import { ThemeBrandProvider } from "./th_2/_components/theme/theme-brand-provider"

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const locale = (cookieStore.get("NEXT_LOCALE")?.value || "en") as "en" | "bn"

  // Use explicit imports instead of dynamic template literals
  const messages =
    locale === "bn"
      ? (await import("@/messages/bn.json")).default
      : (await import("@/messages/en.json")).default

  return (
    <html
      lang={locale}
      className={`${inter.variable} ${geistMono.variable} antialiased`}
    >
      <body>
        <NextIntlClientProvider>
          <ThemeBrandProvider>
            <div style={{ display: "contents" }}>
              <Header />
              {children}
              <Footer />
            </div>
          </ThemeBrandProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
